config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about'     => 'static_pages#about'
  get 'help'      => 'static_pages#help'
  get 'contact'   => 'static_pages#contact'
  get 'signup'    => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :days
  resources :exercises            

end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :user
  has_many :exercises, dependent: :destroy
  default_scope -> { order(workout_date: :desc) }
  validates :content, presence: true
  validates :user_id, presence: true
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  
  def edit
    @day = Day.find(params[:id])
    @exercise = @day.exercises.build
  end
  
  def create
    @day = current_user.days.build(day_params)
    if @day.save
      flash[:success] = "Day created!"
      redirect_to user_path(current_user)
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @day.destroy
    flash[:success] = "Day deleted"
    redirect_to request.referrer || root_url
  end
  
  private

    def day_params
      params.require(:day).permit(:content, :workout_date)
    end
    
    def correct_user
      @day = current_user.days.find_by(id: params[:id])
      redirect_to root_url if @day.nil?
    end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_day.html.erb
<li id="day-<%= day.id %>">
  <span class="date"><%= day.workout_date.to_formatted_s(:long) %></span>
  <%= raw('&nbsp;' * 5) %>
  <span class="content">
    Summary:
    <%= raw('&nbsp;' * 2) %>
    <%= day.content %>
  </span>
  <% if day.exercises.any? %>
    <span class = "mytable">
      <table id="exercises">
        <%= render day.exercises %>
      </table>
    </span>
  <% end %>
  <% if current_user?(day.user) %>
      <li class="add_exercise">
        <%-# should probably go to new_exercise_path but this works -%>
        <%= link_to "Add Exercise", edit_day_path(day) %>
        <span class = "delete_day">
          <%= link_to "delete", day, method: :delete,
                                       data: { confirm: "Are you sure?" } %>
        </span>
      </li>
  <% end %>
</li>

app/views/days/edit.html.erb
<section class="exercise_form">
  <%= render 'shared/exercise_form' %>
</section>